/* GENERATED by tutor/maint/intro-deck/build.mjs from shell.jsx + slides.jsx · source sha256:d5254212eae996fd · do not edit, edit the .jsx and rebuild */
(function () {
"use strict";
const {
  useState,
  useEffect,
  useRef
} = React;
const CANVAS_W = 1280;
const CANVAS_H = 720;
const QS = new URLSearchParams(location.search);
const IS_PRINT = QS.has('print');
const IS_STATIC = IS_PRINT || QS.has('static');
const SHOW_SPEAKER = !QS.has('nospeaker');
const C = {
  IVORY: '#FAF9F5',
  SLATE: '#141413',
  CLAY: '#D97757',
  OAT: '#E3DACC',
  TINT: '#F0EEE6',
  SKY: '#6A9BCC',
  OLIVE: '#788C5D',
  MINERAL: '#629987',
  GRAY: '#73726C',
  LINE: 'rgba(31,30,29,0.12)',
  INK: '#3d3d3a',
  GREEN: '#3d6f60',
  RUST: '#a5482b'
};
const SANS = '"Noto Sans JP", "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Yu Gothic UI", Meiryo, -apple-system, "Segoe UI", system-ui, sans-serif';
const MONO = 'ui-monospace, "SF Mono", Menlo, Consolas, "Noto Sans JP", monospace';
const ph = (...a) => a.map((x, i) => React.createElement("span", {
  key: i,
  style: {
    display: 'inline-block'
  }
}, x));
const nb = t => React.createElement("span", {
  style: {
    whiteSpace: 'nowrap'
  }
}, t);
function Slide({
  bg = C.IVORY,
  color = C.SLATE,
  children,
  label,
  padding = '44px 72px 60px',
  center = false
}) {
  return React.createElement("div", {
    "data-screen-label": label,
    style: {
      position: 'absolute',
      inset: 0,
      background: bg
    }
  }, React.createElement("div", {
    style: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      width: CANVAS_W,
      height: CANVAS_H,
      transform: 'translate(-50%, -50%) scale(var(--deck-scale, 1))',
      color,
      padding,
      display: 'flex',
      flexDirection: 'column',
      fontFamily: SANS,
      overflow: 'hidden',
      lineBreak: 'strict',
      justifyContent: center ? 'center' : 'flex-start',
      alignItems: center ? 'center' : 'stretch'
    }
  }, children));
}
function useLoop(count, ms, fixed) {
  const [i, setI] = useState(IS_STATIC ? fixed : 0);
  useEffect(() => {
    if (IS_STATIC) return undefined;
    const t = setInterval(() => setI(x => (x + 1) % count), ms);
    return () => clearInterval(t);
  }, [count, ms]);
  return i;
}
function readHash(n) {
  const k = parseInt(String(location.hash).replace('#', ''), 10);
  return Number.isFinite(k) && k >= 1 && k <= n ? k - 1 : 0;
}
function Deck({
  slides
}) {
  const N = slides.length;
  const [idx, setIdx] = useState(() => readHash(N));
  const [notes, setNotes] = useState(false);
  const [overview, setOverview] = useState(false);
  const [vw, setVw] = useState(() => window.innerWidth);
  const root = useRef(null);
  const cols = vw >= 1100 ? 4 : vw >= 760 ? 3 : 2;
  useEffect(() => {
    if (IS_PRINT) return undefined;
    const fit = () => {
      const s = Math.min(window.innerWidth / CANVAS_W, window.innerHeight / CANVAS_H);
      if (root.current) root.current.style.setProperty('--deck-scale', String(s));
      setVw(window.innerWidth);
    };
    fit();
    window.addEventListener('resize', fit);
    return () => window.removeEventListener('resize', fit);
  }, []);
  useEffect(() => {
    if (IS_PRINT) return undefined;
    const go = d => setIdx(i => Math.max(0, Math.min(N - 1, i + d)));
    const onKey = e => {
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      const k = e.key;
      if (overview) {
        if (k === 'Escape' || k === 'Enter' || k === ' ') {
          e.preventDefault();
          setOverview(false);
        } else if (k === 'ArrowRight') {
          e.preventDefault();
          go(1);
        } else if (k === 'ArrowLeft') {
          e.preventDefault();
          go(-1);
        } else if (k === 'ArrowDown') {
          e.preventDefault();
          go(cols);
        } else if (k === 'ArrowUp') {
          e.preventDefault();
          go(-cols);
        } else if (k === 'Home') setIdx(0);else if (k === 'End') setIdx(N - 1);
        return;
      }
      if (k === 'Escape') {
        e.preventDefault();
        setOverview(true);
      } else if (k === 'ArrowRight' || k === 'PageDown' || k === ' ' || k === 'Enter') {
        e.preventDefault();
        go(1);
      } else if (k === 'ArrowLeft' || k === 'PageUp' || k === 'Backspace') {
        e.preventDefault();
        go(-1);
      } else if (k === 'Home') setIdx(0);else if (k === 'End') setIdx(N - 1);else if (k === 'n' || k === 'N') setNotes(v => !v);else if (k === 'f' || k === 'F') {
        if (document.fullscreenElement) document.exitFullscreen();else if (document.documentElement.requestFullscreen) document.documentElement.requestFullscreen().catch(() => {});
      }
    };
    const onHash = () => setIdx(readHash(N));
    window.addEventListener('keydown', onKey);
    window.addEventListener('hashchange', onHash);
    return () => {
      window.removeEventListener('keydown', onKey);
      window.removeEventListener('hashchange', onHash);
    };
  }, [N, overview, cols]);
  useEffect(() => {
    if (IS_PRINT) return;
    const want = `#${idx + 1}`;
    if (location.hash !== want) history.replaceState(null, '', want);
    document.title = `${idx + 1} / ${N} · ${slides[idx].title}`;
  }, [idx]);
  if (IS_PRINT) {
    return React.createElement("div", null, slides.map((s, i) => React.createElement("div", {
      key: i,
      className: "print-page",
      style: {
        position: 'relative',
        width: CANVAS_W,
        height: CANVAS_H,
        overflow: 'hidden'
      }
    }, React.createElement(s.c, null))));
  }
  const Cur = slides[idx].c;
  const PAD = 40;
  const GAP = 22;
  const tw = Math.floor((vw - PAD * 2 - GAP * (cols - 1)) / cols);
  const th = Math.round(tw * CANVAS_H / CANVAS_W);
  const btn = (label, d, off) => React.createElement("button", {
    type: "button",
    "aria-label": label,
    disabled: off,
    onClick: () => setIdx(i => Math.max(0, Math.min(N - 1, i + d))),
    style: {
      all: 'unset',
      cursor: off ? 'default' : 'pointer',
      opacity: off ? 0.3 : 1,
      padding: '4px 10px',
      fontSize: 18,
      lineHeight: 1
    }
  }, d < 0 ? '‹' : '›');
  return React.createElement("div", {
    ref: root,
    style: {
      position: 'absolute',
      inset: 0
    }
  }, React.createElement(Cur, {
    key: idx
  }), notes && React.createElement("div", {
    style: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      maxHeight: '34%',
      overflow: 'auto',
      background: 'rgba(20,20,19,0.94)',
      color: '#EDEBE3',
      font: `15px/1.75 ${SANS}`,
      padding: '16px 28px 56px',
      borderTop: `2px solid ${C.CLAY}`
    }
  }, React.createElement("div", {
    style: {
      font: `600 11px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.CLAY,
      marginBottom: 6
    }
  }, "\u8B1B\u5E2B\u7528\u30CE\u30FC\u30C8 \xB7 N \u3067\u9589\u3058\u308B"), slides[idx].notes), overview && React.createElement("div", {
    style: {
      position: 'absolute',
      inset: 0,
      zIndex: 5,
      background: C.SLATE,
      overflow: 'auto',
      padding: `28px ${PAD}px 64px`,
      fontFamily: SANS
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'baseline',
      gap: 16,
      marginBottom: 20
    }
  }, React.createElement("span", {
    style: {
      fontSize: 22,
      fontWeight: 700,
      color: C.IVORY
    }
  }, "\u30DA\u30FC\u30B8\u4E00\u89A7"), React.createElement("span", {
    style: {
      font: `12px/1.4 ${MONO}`,
      color: 'rgba(250,249,245,0.6)'
    }
  }, "\u30AF\u30EA\u30C3\u30AF\u3067\u305D\u306E\u30DA\u30FC\u30B8\u3078 \xB7 \u77E2\u5370\u30AD\u30FC\u3067\u9078\u3093\u3067 Enter \xB7 Esc \u3067\u623B\u308B")), React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: `repeat(${cols}, ${tw}px)`,
      gap: `${GAP}px`
    }
  }, slides.map((s, i) => React.createElement("div", {
    key: i,
    role: "button",
    tabIndex: -1,
    "aria-label": `${i + 1} ページへ`,
    onClick: () => {
      setIdx(i);
      setOverview(false);
    },
    ref: i === idx ? el => {
      if (el && el.scrollIntoView) el.scrollIntoView({
        block: 'nearest'
      });
    } : null,
    style: {
      cursor: 'pointer'
    }
  }, React.createElement("div", {
    style: {
      position: 'relative',
      width: tw,
      height: th,
      overflow: 'hidden',
      borderRadius: 8,
      outline: i === idx ? `3px solid ${C.CLAY}` : '1px solid rgba(250,249,245,0.2)',
      outlineOffset: i === idx ? 3 : 0,
      '--deck-scale': String(tw / CANVAS_W)
    }
  }, React.createElement(s.c, null), React.createElement("div", {
    style: {
      position: 'absolute',
      inset: 0
    }
  })), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 8,
      marginTop: 8,
      fontSize: 12.5,
      lineHeight: 1.45,
      color: i === idx ? C.IVORY : 'rgba(250,249,245,0.72)'
    }
  }, React.createElement("span", {
    style: {
      font: `600 12px/1.5 ${MONO}`,
      color: C.CLAY,
      flexShrink: 0
    }
  }, String(i + 1).padStart(2, '0')), React.createElement("span", null, s.title)))))), React.createElement("div", {
    style: {
      position: 'absolute',
      left: 0,
      bottom: 0,
      height: 3,
      width: `${(idx + 1) / N * 100}%`,
      background: C.CLAY,
      transition: 'width 0.3s ease',
      zIndex: 6
    }
  }), React.createElement("div", {
    style: {
      position: 'absolute',
      right: 14,
      bottom: 12,
      display: 'flex',
      alignItems: 'center',
      gap: 2,
      background: 'rgba(20,20,19,0.78)',
      color: '#FAF9F5',
      border: '1px solid rgba(250,249,245,0.22)',
      borderRadius: 999,
      padding: '3px 6px',
      font: `12px/1 ${MONO}`,
      userSelect: 'none',
      zIndex: 6
    }
  }, React.createElement("button", {
    type: "button",
    "aria-label": "\u30DA\u30FC\u30B8\u4E00\u89A7",
    title: "\u30DA\u30FC\u30B8\u4E00\u89A7\uFF08Esc\uFF09",
    onClick: () => setOverview(v => !v),
    style: {
      all: 'unset',
      cursor: 'pointer',
      padding: '4px 8px 4px 10px',
      display: 'inline-flex'
    }
  }, React.createElement("svg", {
    viewBox: "0 0 14 14",
    width: "13",
    height: "13",
    "aria-hidden": "true"
  }, React.createElement("path", {
    d: "M1 1h5v5H1zM8 1h5v5H8zM1 8h5v5H1zM8 8h5v5H8z",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.4"
  }))), btn('前のページ', -1, idx === 0), React.createElement("span", {
    style: {
      minWidth: 52,
      textAlign: 'center'
    }
  }, idx + 1, " / ", N), btn('次のページ', 1, idx === N - 1)), !overview && React.createElement("div", {
    style: {
      position: 'absolute',
      left: 14,
      bottom: 12,
      font: `12px/1 ${MONO}`,
      color: 'rgba(115,114,108,0.9)',
      userSelect: 'none'
    }
  }, "\u2190 \u2192 \u3067\u79FB\u52D5 \xB7 Esc \u4E00\u89A7 \xB7 N \u30CE\u30FC\u30C8 \xB7 F \u5168\u753B\u9762"));
}
function mountDeck(slides) {
  if (IS_PRINT) document.documentElement.classList.add('print');
  ReactDOM.createRoot(document.getElementById('deck-root')).render(React.createElement(Deck, {
    slides: slides
  }));
}

function Head({
  kicker,
  h2,
  sub,
  dark
}) {
  return React.createElement("div", {
    style: {
      marginBottom: 18
    }
  }, React.createElement("div", {
    style: {
      font: `600 12.5px/1.4 ${MONO}`,
      letterSpacing: '0.14em',
      textTransform: 'uppercase',
      color: C.CLAY,
      marginBottom: 9
    }
  }, kicker), React.createElement("h2", {
    style: {
      font: `700 35px/1.28 ${SANS}`,
      letterSpacing: '-0.01em',
      margin: 0,
      color: dark ? C.IVORY : C.SLATE
    }
  }, h2), sub && React.createElement("div", {
    style: {
      fontSize: 16.5,
      lineHeight: 1.6,
      color: dark ? 'rgba(250,249,245,0.72)' : C.GRAY,
      marginTop: 8,
      maxWidth: '80%'
    }
  }, sub));
}
const code = (t, size) => React.createElement("code", {
  style: {
    fontFamily: MONO,
    fontSize: size || 13.5,
    background: C.TINT,
    padding: '2px 6px',
    borderRadius: 5,
    whiteSpace: 'nowrap'
  }
}, t);
function Pin({
  n,
  c,
  size,
  style
}) {
  const d = size || 22;
  return React.createElement("span", {
    style: Object.assign({
      flex: '0 0 auto',
      width: d,
      height: d,
      borderRadius: d / 2,
      background: c || C.CLAY,
      color: '#fff',
      fontFamily: MONO,
      fontSize: d * 0.57,
      fontWeight: 700,
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: '0 0 0 3px rgba(255,255,255,0.92), 0 2px 8px rgba(20,20,19,0.35)'
    }, style)
  }, n);
}
function Slide_Title() {
  const dot = (c, k) => React.createElement("span", {
    key: k,
    style: {
      width: 10,
      height: 10,
      borderRadius: 5,
      background: c,
      display: 'inline-block'
    }
  });
  const lbl = {
    font: `600 13px/1 ${MONO}`,
    letterSpacing: '0.08em',
    color: 'rgba(250,249,245,0.72)',
    whiteSpace: 'nowrap'
  };
  return React.createElement(Slide, {
    bg: C.SLATE,
    color: C.IVORY,
    label: "Title",
    padding: "0 112px"
  }, React.createElement("div", {
    style: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      height: '100%'
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 14,
      marginBottom: 30
    }
  }, React.createElement("span", {
    style: {
      width: 44,
      height: 4,
      background: C.CLAY,
      display: 'inline-block',
      borderRadius: 2
    }
  }), React.createElement("span", {
    style: {
      font: `600 13px/1 ${MONO}`,
      letterSpacing: '0.16em',
      color: C.CLAY,
      border: `1.5px solid ${C.CLAY}`,
      borderRadius: 999,
      padding: '7px 14px'
    }
  }, "\u30D1\u30FC\u30C8\u30CA\u30FC\u5411\u3051")), React.createElement("div", {
    style: {
      fontSize: 68,
      lineHeight: 1.12,
      fontWeight: 700,
      letterSpacing: '-0.015em',
      whiteSpace: 'nowrap'
    }
  }, "Claude \u304C Claude \u3092\u6559\u3048\u308B"), React.createElement("div", {
    style: {
      fontSize: 33,
      fontWeight: 500,
      color: C.CLAY,
      marginTop: 16
    }
  }, "\u30BB\u30EB\u30D5\u30DA\u30FC\u30B9\u578B Claude \u30CF\u30F3\u30BA\u30AA\u30F3\u30EF\u30FC\u30AF\u30B7\u30E7\u30C3\u30D7"), React.createElement("div", {
    style: {
      fontSize: 18.5,
      color: 'rgba(250,249,245,0.76)',
      marginTop: 34,
      lineHeight: 1.75
    }
  }, "Meridian Components \u306E RFP \u306B\u5FDC\u672D\u3057\u3001\u6700\u521D\u306E\u6539\u4FEE\u3092\u7D0D\u54C1\u3057\u307E\u3059 \xB7 ", nb('約 90 分'), React.createElement("br", null), "\u81EA\u5206\u306E\u30BF\u30FC\u30DF\u30CA\u30EB\u3067\u3001Claude \u304C ", nb('1 ステップ'), "\u305A\u3064\u6848\u5185\u3057\u307E\u3059\u3002"), React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      marginTop: 44
    }
  }, React.createElement("span", {
    style: lbl
  }, "\u7B2C1\u5E55 \xB7 \u5FDC\u672D"), React.createElement("span", {
    style: {
      display: 'inline-flex',
      gap: 6
    }
  }, [0, 1, 2, 3, 4, 5, 6].map(i => dot(C.SKY, i))), React.createElement("span", {
    style: Object.assign({}, lbl, {
      color: C.CLAY
    })
  }, "\u2192 \u53D7\u6CE8 \u2192"), React.createElement("span", {
    style: lbl
  }, "\u7B2C2\u5E55 \xB7 \u7D0D\u54C1"), React.createElement("span", {
    style: {
      display: 'inline-flex',
      gap: 6
    }
  }, [0, 1, 2, 3].map(i => dot(C.CLAY, i))), React.createElement("span", {
    style: {
      width: 12,
      height: 14,
      borderRadius: 2,
      border: '2px solid #9CC3B5',
      display: 'inline-block'
    }
  }), React.createElement("span", {
    style: Object.assign({}, lbl, {
      color: '#9CC3B5'
    })
  }, "\u9032\u6357\u30EC\u30DD\u30FC\u30C8"))));
}
function Slide_Speaker() {
  const P = window.PRESENTER || {};
  const initials = String(P.name || '').split(/\s+/).filter(Boolean).map(w => w[0]).join('').slice(0, 2).toUpperCase();
  const career = P.career || [];
  return React.createElement(Slide, {
    label: "Speaker",
    padding: "44px 72px 60px"
  }, React.createElement("div", {
    style: {
      display: 'flex',
      gap: 56,
      flex: 1,
      minHeight: 0,
      alignItems: 'center'
    }
  }, React.createElement("div", {
    style: {
      flex: 0.82,
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      font: `600 12.5px/1.4 ${MONO}`,
      letterSpacing: '0.14em',
      color: C.CLAY,
      marginBottom: 26
    }
  }, "\u8B1B\u5E2B\u7D39\u4ECB"), P.photo ? React.createElement("img", {
    src: P.photo,
    alt: "",
    style: {
      width: 132,
      height: 132,
      borderRadius: 66,
      objectFit: 'cover',
      boxShadow: `0 0 0 4px ${C.IVORY}, 0 0 0 6px ${C.CLAY}`
    }
  }) : React.createElement("div", {
    style: {
      width: 132,
      height: 132,
      borderRadius: 66,
      background: C.SLATE,
      color: C.IVORY,
      fontSize: 46,
      fontWeight: 700,
      letterSpacing: '0.04em',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: `0 0 0 4px ${C.IVORY}, 0 0 0 6px ${C.CLAY}`
    }
  }, initials), React.createElement("div", {
    style: {
      fontSize: 56,
      fontWeight: 700,
      lineHeight: 1.15,
      letterSpacing: '-0.015em',
      marginTop: 26
    }
  }, P.name), React.createElement("div", {
    style: {
      fontSize: 25,
      fontWeight: 500,
      color: C.CLAY,
      marginTop: 10
    }
  }, P.role), React.createElement("div", {
    style: {
      fontSize: 20,
      color: C.GRAY,
      marginTop: 4
    }
  }, P.org)), React.createElement("div", {
    style: {
      flex: 1.18,
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.GRAY,
      marginBottom: 14
    }
  }, "\u7D4C\u6B74"), React.createElement("div", {
    style: {
      position: 'relative',
      paddingLeft: 34
    }
  }, React.createElement("span", {
    style: {
      position: 'absolute',
      left: 8,
      top: 10,
      bottom: 22,
      width: 2,
      background: C.OAT
    }
  }), career.map((c, i) => React.createElement("div", {
    key: i,
    style: {
      position: 'relative',
      paddingBottom: i === career.length - 1 ? 0 : 20
    }
  }, React.createElement("span", {
    style: {
      position: 'absolute',
      left: -34,
      top: 5,
      width: 18,
      height: 18,
      borderRadius: 9,
      background: i === 0 ? C.CLAY : C.IVORY,
      border: `2.5px solid ${i === 0 ? C.CLAY : C.SKY}`
    }
  }), React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'baseline',
      gap: 14
    }
  }, React.createElement("span", {
    style: {
      font: `600 14px/1.4 ${MONO}`,
      color: i === 0 ? C.RUST : C.GRAY,
      width: 104,
      flexShrink: 0
    }
  }, c.years), React.createElement("span", {
    style: {
      fontSize: 21,
      fontWeight: 700,
      lineHeight: 1.3
    }
  }, c.org)), c.role && React.createElement("div", {
    style: {
      fontSize: 15,
      color: C.INK,
      lineHeight: 1.5,
      paddingLeft: 118,
      marginTop: 1
    }
  }, c.role)))))));
}
function TermLine({
  who,
  children,
  dim
}) {
  const c = who === 'you' ? C.CLAY : who === 'check' ? '#9CC3B5' : 'rgba(250,249,245,0.92)';
  return React.createElement("div", {
    style: {
      display: 'flex',
      gap: 10,
      fontFamily: MONO,
      fontSize: 14.5,
      lineHeight: 1.65,
      opacity: dim ? 0.55 : 1
    }
  }, React.createElement("span", {
    style: {
      color: c,
      width: 58,
      flexShrink: 0,
      textAlign: 'right'
    }
  }, who === 'check' ? '✓' : who), React.createElement("span", {
    style: {
      color: who === 'you' ? C.IVORY : c
    }
  }, children));
}
function Slide_How() {
  const beat = (n, t, s, c) => React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      marginBottom: 3
    }
  }, React.createElement("span", {
    style: {
      width: 22,
      height: 22,
      borderRadius: 11,
      background: c,
      color: '#fff',
      fontSize: 12,
      fontWeight: 700,
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0
    }
  }, n), React.createElement("span", {
    style: {
      fontWeight: 700,
      fontSize: 15
    }
  }, t)), React.createElement("div", {
    style: {
      fontSize: 12.5,
      lineHeight: 1.5,
      color: C.GRAY,
      paddingLeft: 30
    }
  }, s));
  const days = [['4/17', '発行'], ['4/28', '質問'], ['5/8', '提出']];
  return React.createElement(Slide, {
    label: "How it works",
    padding: "40px 72px 58px"
  }, React.createElement(Head, {
    kicker: "\u9032\u307F\u65B9",
    h2: ph('Claude が 1 ステップずつ案内し、', 'あなたが判断して手を動かす')
  }), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 22,
      flex: 1,
      minHeight: 0
    }
  }, React.createElement("div", {
    style: {
      flex: 1.2,
      background: C.SLATE,
      borderRadius: 14,
      padding: '16px 20px',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      gap: 10,
      boxShadow: '0 10px 30px rgba(0,0,0,0.18)'
    }
  }, React.createElement("div", {
    style: {
      fontFamily: MONO,
      fontSize: 11,
      color: 'rgba(250,249,245,0.45)',
      marginBottom: 4
    }
  }, "~/meridian-workshop-jp \xB7 claude"), React.createElement(TermLine, {
    who: "claude"
  }, "\u30B9\u30C6\u30C3\u30D7 03 \xB7 4 \u5206\u3002Meridian \u304B\u3089\u5C4A\u3044\u305F RFP \u3092\u8AAD\u307F\u307E\u3057\u3087\u3046\u3002\u6B21\u306F\u3001\u3042\u306A\u305F\u304C\u5165\u529B\u3057\u307E\u3059\u3002"), React.createElement(TermLine, {
    who: "you"
  }, "@docs/rfp/MC-2026-0417.md \u3092\u8AAD\u3093\u3067\u3001\u79C1\u305F\u3061\u306E\u7406\u89E3\u3092\u6574\u7406\u3057\u3066\u304F\u3060\u3055\u3044"), React.createElement(TermLine, {
    who: "claude",
    dim: true
  }, "\u2026RFP \u3068\u80CC\u666F\u8CC7\u6599\u3092\u8AAD\u307F\u3001\u4F9D\u983C\u306E\u5185\u5BB9\u3001\u5FC5\u9808\u3068\u5E0C\u671B\u3001\u65E5\u7A0B\u3001\u8A55\u4FA1\u914D\u70B9\u3092\u6574\u7406"), React.createElement(TermLine, {
    who: "claude"
  }, "\u540C\u3058\u5185\u5BB9\u3092\u56F3\u306B\u3057\u305F\u30DA\u30FC\u30B8\u3092\u958B\u304D\u307E\u3057\u305F\u3002\u8AAD\u307F\u7D42\u3048\u305F\u3089\u300CDone\u300D\u3068\u9001\u3063\u3066\u304F\u3060\u3055\u3044\u3002"), React.createElement(TermLine, {
    who: "you"
  }, "Done"), React.createElement(TermLine, {
    who: "check"
  }, "RFP \u306E\u7406\u89E3\u304C\u8A18\u9332\u3055\u308C\u3066\u3044\u308B"), React.createElement(TermLine, {
    who: "claude"
  }, "\u30B9\u30C6\u30C3\u30D7 04 \xB7 6 \u5206\u3002\u3053\u306E RFP \u3067\u3001\u6C7A\u3081\u306A\u3044\u3068\u898B\u7A4D\u3082\u308C\u306A\u3044\u3068\u3053\u308D\u306F\u3069\u3053\u3067\u3057\u3087\u3046\uFF1F")), React.createElement("div", {
    style: {
      flex: 0.8,
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      flex: 1,
      background: '#fff',
      border: `1px solid ${C.LINE}`,
      borderRadius: 14,
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0
    }
  }, React.createElement("div", {
    style: {
      background: C.TINT,
      padding: '7px 12px',
      fontFamily: MONO,
      fontSize: 11,
      color: C.GRAY
    }
  }, "localhost:8766 \xB7 \u3042\u306A\u305F\u306E\u30DE\u30B7\u30F3\u304B\u3089\u914D\u4FE1"), React.createElement("div", {
    style: {
      padding: '12px 18px'
    }
  }, React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.CLAY
    }
  }, "\u7B2C1\u5E55 \xB7 \u30B9\u30C6\u30C3\u30D7 03 \xB7 \u79C1\u305F\u3061\u306E\u7406\u89E3"), React.createElement("div", {
    style: {
      fontSize: 18.5,
      fontWeight: 700,
      lineHeight: 1.4,
      margin: '5px 0 14px'
    }
  }, "\u4ECA\u56DE\u306E RFP \u3092\u8AAD\u307F\u89E3\u304F"), React.createElement("div", {
    style: {
      position: 'relative',
      display: 'flex',
      justifyContent: 'space-between',
      padding: '0 10px'
    }
  }, React.createElement("span", {
    style: {
      position: 'absolute',
      left: 24,
      right: 24,
      top: 7,
      height: 2,
      background: C.OAT
    }
  }), days.map(([d, t], i) => React.createElement("span", {
    key: t,
    style: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 4
    }
  }, React.createElement("span", {
    style: {
      width: 16,
      height: 16,
      borderRadius: 8,
      background: i === 2 ? C.CLAY : '#fff',
      border: `2px solid ${i === 2 ? C.CLAY : C.SKY}`
    }
  }), React.createElement("span", {
    style: {
      font: `600 12px/1 ${MONO}`
    }
  }, d), React.createElement("span", {
    style: {
      fontSize: 12,
      color: C.GRAY
    }
  }, t)))), React.createElement("div", {
    style: {
      marginTop: 14,
      borderTop: `1px solid ${C.LINE}`,
      paddingTop: 10,
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '7px 14px',
      fontSize: 13,
      color: C.INK
    }
  }, ['1 · スケジュール', '2 · 必須と希望', '3 · 評価配点', '4 · 意思決定者', '5 · 求められている提案書', '6 · 勝ち筋の候補'].map(t => React.createElement("span", {
    key: t,
    style: {
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis'
    }
  }, t))))), React.createElement("div", {
    style: {
      background: '#fff',
      border: `1.5px solid ${C.MINERAL}`,
      borderRadius: 12,
      padding: '10px 14px',
      fontSize: 13.5,
      lineHeight: 1.6
    }
  }, React.createElement("b", {
    style: {
      color: C.GREEN
    }
  }, "\u300CDone\u300D\u306E\u3042\u3068\u306F\u3001Claude \u304C\u78BA\u304B\u3081\u307E\u3059\u3002"), "\u30D5\u30A1\u30A4\u30EB\u3001\u30D6\u30E9\u30F3\u30C1\u3001\u30B3\u30DF\u30C3\u30C8\u3001\u8D77\u52D5\u4E2D\u306E\u30A2\u30D7\u30EA\u3092\u898B\u3066\u304B\u3089\u3001\u6B21\u3078\u9032\u307F\u307E\u3059\u3002"))), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 14,
      marginTop: 12,
      paddingTop: 11,
      borderTop: `1px solid ${C.LINE}`
    }
  }, beat(1, 'Claude が説明する', '目安の時間も伝える', C.SLATE), beat(2, 'あなたが手を動かす', '読む、決める、/start や @ の入力', C.SKY), beat(3, '「Done」と伝える', '「できました」でも構いません', C.CLAY), beat(4, 'Claude が確かめる', 'リポジトリの状態と記録を見て', C.MINERAL), beat(5, '次のステップへ', '全部で 12 ステップ', C.SLATE)));
}
function FileIcon({
  kind
}) {
  const s = {
    width: 28,
    height: 28,
    flexShrink: 0
  };
  if (kind === 'code') {
    return React.createElement("svg", {
      viewBox: "0 0 26 26",
      style: s,
      "aria-hidden": "true"
    }, React.createElement("path", {
      d: "M3 7.5a2 2 0 0 1 2-2h5l2 2.5h9a2 2 0 0 1 2 2V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
      fill: "none",
      stroke: C.SKY,
      strokeWidth: "1.8"
    }), React.createElement("path", {
      d: "M11 12.5 8.8 15l2.2 2.5M15 12.5l2.2 2.5-2.2 2.5",
      fill: "none",
      stroke: C.SKY,
      strokeWidth: "1.6",
      strokeLinecap: "round",
      strokeLinejoin: "round"
    }));
  }
  const stroke = kind === 'memo' ? C.OLIVE : kind === 'note' ? C.MINERAL : C.CLAY;
  return React.createElement("svg", {
    viewBox: "0 0 26 26",
    style: s,
    "aria-hidden": "true"
  }, React.createElement("path", {
    d: "M6 3.5h9.5L20 8v14.5H6z",
    fill: "none",
    stroke: stroke,
    strokeWidth: "1.8",
    strokeLinejoin: "round"
  }), React.createElement("path", {
    d: "M15.5 3.5V8H20",
    fill: "none",
    stroke: stroke,
    strokeWidth: "1.8",
    strokeLinejoin: "round"
  }), React.createElement("path", {
    d: "M9 12.5h8M9 15.5h8M9 18.5h5",
    stroke: stroke,
    strokeWidth: "1.5",
    strokeLinecap: "round"
  }));
}
function Slide_Case() {
  const req = (id, t, top) => React.createElement("div", {
    key: id,
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      padding: '7px 0',
      borderBottom: `1px solid ${C.LINE}`,
      fontSize: 15.5
    }
  }, React.createElement("b", {
    style: {
      fontFamily: MONO,
      fontSize: 13,
      width: 26,
      color: top ? C.RUST : C.GRAY
    }
  }, id), React.createElement("span", {
    style: {
      fontWeight: top ? 700 : 400
    }
  }, t), top && React.createElement("span", {
    style: {
      marginLeft: 'auto',
      font: `600 12px/1 ${MONO}`,
      letterSpacing: '0.08em',
      color: '#fff',
      background: C.CLAY,
      borderRadius: 6,
      padding: '5px 8px',
      whiteSpace: 'nowrap'
    }
  }, "\u6700\u512A\u5148"));
  const day = (d, t, on) => React.createElement("span", {
    key: t,
    style: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 4
    }
  }, React.createElement("span", {
    style: {
      width: 14,
      height: 14,
      borderRadius: 7,
      background: on ? C.CLAY : '#fff',
      border: `2px solid ${on ? C.CLAY : C.SKY}`
    }
  }), React.createElement("span", {
    style: {
      font: `600 12px/1 ${MONO}`,
      color: C.SLATE
    }
  }, d), React.createElement("span", {
    style: {
      fontSize: 12,
      color: C.GRAY
    }
  }, t));
  const file = (kind, path, what) => React.createElement("div", {
    style: {
      display: 'flex',
      gap: 16,
      alignItems: 'center',
      padding: '17px 0',
      borderBottom: `1px solid ${C.LINE}`
    }
  }, React.createElement(FileIcon, {
    kind: kind
  }), React.createElement("div", {
    style: {
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      fontFamily: MONO,
      fontSize: 15.5,
      color: C.SLATE,
      overflowWrap: 'anywhere'
    }
  }, path), React.createElement("div", {
    style: {
      fontSize: 15.5,
      color: C.GRAY,
      marginTop: 3
    }
  }, what)));
  return React.createElement(Slide, {
    label: "The case",
    padding: "40px 72px 58px"
  }, React.createElement(Head, {
    kicker: "\u3042\u306A\u305F\u306E\u5F79",
    h2: ph('あなたはコンサルタント。', 'Meridian Components から RFP が届いた')
  }), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 34,
      flex: 1,
      minHeight: 0
    }
  }, React.createElement("div", {
    style: {
      flex: 1.08,
      minWidth: 0,
      background: '#fff',
      border: `1px solid ${C.LINE}`,
      borderRadius: 6,
      padding: '18px 26px 16px',
      boxShadow: '0 14px 34px rgba(20,20,19,0.12)',
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      borderBottom: `2px solid ${C.SLATE}`,
      paddingBottom: 8
    }
  }, React.createElement("span", {
    style: {
      fontSize: 19,
      fontWeight: 700
    }
  }, "\u63D0\u6848\u4F9D\u983C\u66F8\uFF08RFP\uFF09"), React.createElement("span", {
    style: {
      fontFamily: MONO,
      fontSize: 12.5,
      color: C.GRAY
    }
  }, "MC-2026-0417")), React.createElement("div", {
    style: {
      fontSize: 13.5,
      color: C.INK,
      lineHeight: 1.6,
      margin: '8px 0 6px'
    }
  }, React.createElement("b", null, "Meridian Components, Inc."), " \xB7 \u7523\u696D\u7528\u30AA\u30FC\u30C8\u30E1\u30FC\u30B7\u30E7\u30F3\u90E8\u54C1\u306E\u30C7\u30A3\u30B9\u30C8\u30EA\u30D3\u30E5\u30FC\u30BF\u30FC\u3002\u5009\u5EAB\u306F\u30B5\u30F3\u30D5\u30E9\u30F3\u30B7\u30B9\u30B3\u3001\u30ED\u30F3\u30C9\u30F3\u3001\u6771\u4EAC\u3002", React.createElement("br", null), "\u4F9D\u983C\uFF1A", React.createElement("b", null, "\u5728\u5EAB\u7BA1\u7406\u30C0\u30C3\u30B7\u30E5\u30DC\u30FC\u30C9\u306E\u30E2\u30C0\u30CA\u30A4\u30BA\u3068\u6A5F\u80FD\u62E1\u5F35")), React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.1em',
      color: C.GRAY,
      marginTop: 4
    }
  }, "\u5FC5\u9808\u9805\u76EE\uFF08\u512A\u5148\u9806\u4F4D\u9806\uFF09"), req('R1', '概要ページ（ダッシュボード）の改修', true), req('R2', 'Reports モジュールの改修'), req('R3', '発注推奨機能（新規）'), req('R4', 'ブラウザテストの自動化'), req('R5', 'アーキテクチャドキュメント'), React.createElement("div", {
    style: {
      fontSize: 13,
      color: C.GRAY,
      marginTop: 7
    }
  }, "\u5E0C\u671B\u9805\u76EE\uFF1AD1 UI \u306E\u30E2\u30C0\u30CA\u30A4\u30BA \xB7 D2 \u56FD\u969B\u5316\u5BFE\u5FDC \xB7 D3 \u30C0\u30FC\u30AF\u30E2\u30FC\u30C9"), React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.1em',
      color: C.GRAY,
      marginTop: 14,
      marginBottom: 5
    }
  }, "\u8A55\u4FA1\u57FA\u6E96\uFF08\u914D\u70B9\u6BD4\u7387\uFF09"), React.createElement("div", {
    style: {
      display: 'flex',
      height: 26,
      borderRadius: 6,
      overflow: 'hidden',
      fontSize: 12.5,
      fontWeight: 500,
      color: '#fff'
    }
  }, [['技術アプローチと要件理解 40%', 40, C.SLATE], ['関連実績 25%', 25, C.SKY], ['スケジュール 20%', 20, C.MINERAL], ['価格 15%', 15, C.CLAY]].map(([t, w, c]) => React.createElement("span", {
    key: t,
    style: {
      flex: w,
      background: c,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      whiteSpace: 'nowrap',
      overflow: 'hidden'
    }
  }, t))), React.createElement("div", {
    style: {
      position: 'relative',
      display: 'flex',
      justifyContent: 'space-between',
      marginTop: 'auto',
      padding: '10px 18px 0'
    }
  }, React.createElement("span", {
    style: {
      position: 'absolute',
      left: 30,
      right: 30,
      top: 16,
      height: 2,
      background: C.OAT
    }
  }), day('4/17', '発行'), day('4/28', '質問の締切'), day('5/8', '提案の提出', true))), React.createElement("div", {
    style: {
      flex: 0.92,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.GRAY
    }
  }, "\u624B\u5143\u306B\u3042\u308B\u8CC7\u6599"), file('doc', 'docs/rfp/MC-2026-0417.md', 'RFP の本体'), file('note', 'docs/rfp/meridian-background.md', '自社でまとめた、クライアントの背景メモ'), file('memo', 'docs/rfp/vendor-handoff.md', '前任ベンダーの引き継ぎメモ'), file('code', 'client/ · server/', '前任ベンダーが残したソースコード'), React.createElement("div", {
    style: {
      marginTop: 'auto',
      background: C.SLATE,
      color: C.IVORY,
      borderRadius: 12,
      padding: '14px 20px'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 19,
      fontWeight: 700,
      lineHeight: 1.4,
      marginBottom: 4
    }
  }, "\u30A8\u30F3\u30B8\u30CB\u30A2\u3067\u306A\u304F\u3066\u3082\u9032\u3081\u3089\u308C\u307E\u3059"), React.createElement("div", {
    style: {
      fontSize: 15,
      color: 'rgba(250,249,245,0.82)',
      lineHeight: 1.6
    }
  }, "\u6C7A\u3081\u308B\u306E\u306F\u3042\u306A\u305F\u3002\u6587\u7AE0\u3068\u30B3\u30FC\u30C9\u306F Claude \u304C\u66F8\u304D\u307E\u3059\u3002")))));
}
const STEPS_P1 = [['00', 'ようこそ · 環境の確認と「いまどこ？」', 3], ['01', '読む：このワークショップの進め方', 4], ['02', '読む：RFP とは', 4], ['03', 'RFP を読み込み、理解を整理する', 4, '@ でファイルを参照'], ['04', 'RFP の穴を探す', 6], ['05', '提案の方針を決める · 提案書は Claude が書く', 8, '選択式の質問'], ['06', 'HTML ページとスライドにする', 5]];
const STEPS_P2 = [['07', '受注 · アプリを起動して症状を確かめる', 6, '/start（カスタムコマンド）'], ['08', 'R1 の原因を調べて計画する', 6, 'Plan Mode（Shift+Tab）'], ['09', 'R1 を直し、ブラウザで確かめてコミット', 22], ['10', 'コードレビュー · 直す指摘を選ぶ', 10, 'サブエージェント'], ['11', 'まとめ · 進捗レポート', 7]];
function Slide_Agenda() {
  const rowOf = color => ([n, t, m, chip]) => React.createElement("div", {
    key: n
  }, React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'baseline',
      gap: 8,
      fontSize: 15.5
    }
  }, React.createElement("span", {
    style: {
      font: `12px/1 ${MONO}`,
      color: C.GRAY,
      width: 20,
      flexShrink: 0
    }
  }, n), React.createElement("span", {
    style: {
      fontWeight: 500,
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis'
    }
  }, t), chip && React.createElement("span", {
    style: {
      marginLeft: 'auto',
      fontSize: 12.5,
      padding: '3px 8px',
      borderRadius: 6,
      background: '#D9775722',
      border: '1px solid #D9775755',
      color: C.RUST,
      whiteSpace: 'nowrap',
      flexShrink: 0
    }
  }, chip)), React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
      paddingLeft: 28
    }
  }, React.createElement("span", {
    style: {
      height: 11,
      width: `${m / 22 * 86}%`,
      background: color,
      borderRadius: 6
    }
  }), React.createElement("span", {
    style: {
      font: `12px/1 ${MONO}`,
      color: C.GRAY,
      whiteSpace: 'nowrap'
    }
  }, m, " \u5206")));
  const part = (flex, bg, k, title, mins, rows, color) => React.createElement("div", {
    style: {
      flex,
      background: bg,
      borderRadius: 14,
      padding: '14px 20px 8px',
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      marginBottom: 12
    }
  }, React.createElement("span", null, React.createElement("span", {
    style: {
      font: `600 12px/1 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.CLAY,
      marginRight: 10
    }
  }, k), React.createElement("b", {
    style: {
      fontSize: 19
    }
  }, title)), React.createElement("span", {
    style: {
      font: `13px/1 ${MONO}`,
      color: C.GRAY,
      whiteSpace: 'nowrap'
    }
  }, "\u7D04 ", mins, " \u5206")), React.createElement("div", {
    style: {
      flex: 1,
      minHeight: 0,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-around',
      paddingBottom: 6
    }
  }, rows.map(rowOf(color))));
  return React.createElement(Slide, {
    label: "Agenda",
    padding: "38px 72px 56px"
  }, React.createElement(Head, {
    kicker: "\u4ECA\u65E5\u306E\u6D41\u308C",
    h2: ph('応札する第1幕、', '納品する第2幕、', '最後に進捗レポート')
  }), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 16,
      flex: 1,
      minHeight: 0
    }
  }, part(1, C.TINT, '第1幕', 'RFP に応札する', 34, STEPS_P1, C.SKY), part(1, '#F4E9E3', '第2幕', '受注した案件を納品する', 51, STEPS_P2, C.CLAY)), React.createElement("div", {
    style: {
      marginTop: 10,
      fontSize: 13.5,
      lineHeight: 1.6,
      color: C.GRAY,
      display: 'flex',
      justifyContent: 'space-between',
      gap: 24
    }
  }, React.createElement("span", null, "\u5408\u8A08 ", nb('約 85 分'), " + \u4E88\u5099 ", nb('約 5 分'), " = \u4E88\u7B97 ", nb('90 分')), React.createElement("span", null, React.createElement("span", {
    style: {
      color: C.RUST
    }
  }, "\u8272\u4ED8\u304D\u306E\u30E9\u30D9\u30EB"), " = \u305D\u306E\u30B9\u30C6\u30C3\u30D7\u3067\u521D\u3081\u3066\u4F7F\u3046 Claude Code \u306E\u6A5F\u80FD")));
}
const APP = {
  bg: '#f8fafc',
  card: '#ffffff',
  ink: '#0f172a',
  sub: '#64748b',
  line: '#e2e8f0',
  blue: '#2563eb',
  blueBg: '#eff6ff',
  green: '#10b981'
};
function AppMock({
  phase
}) {
  const sel = (label, value, on) => React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      fontSize: 10.5,
      color: APP.sub,
      marginBottom: 3
    }
  }, label), React.createElement("div", {
    style: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      background: '#fff',
      border: '1px solid #cbd5e1',
      borderRadius: 6,
      padding: '5px 8px',
      fontSize: 12,
      color: APP.ink,
      outline: `2.5px solid ${on ? C.CLAY : 'transparent'}`,
      outlineOffset: 2,
      transition: 'outline-color 0.35s ease'
    }
  }, React.createElement("span", {
    style: {
      whiteSpace: 'nowrap',
      overflow: 'hidden'
    }
  }, value), React.createElement("span", {
    style: {
      color: APP.sub,
      fontSize: 9
    }
  }, "\u25BC")));
  const kpi = (label, value, goal, w, ok, flex) => React.createElement("div", {
    style: {
      flex: flex || 1,
      minWidth: 0,
      background: APP.card,
      border: `1px solid ${APP.line}`,
      borderRadius: 9,
      padding: '8px 9px'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 10,
      color: APP.sub,
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis'
    }
  }, label), React.createElement("div", {
    style: {
      fontSize: 18,
      fontWeight: 700,
      color: APP.ink,
      margin: '2px 0 1px',
      whiteSpace: 'nowrap'
    }
  }, value), React.createElement("div", {
    style: {
      fontSize: 9,
      color: APP.sub,
      whiteSpace: 'nowrap',
      overflow: 'hidden'
    }
  }, goal), React.createElement("div", {
    style: {
      height: 4,
      background: APP.line,
      borderRadius: 2,
      marginTop: 5
    }
  }, React.createElement("div", {
    style: {
      width: w,
      height: '100%',
      background: ok ? APP.green : APP.blue,
      borderRadius: 2
    }
  })));
  const tab = (t, on) => React.createElement("span", {
    key: t,
    style: {
      fontSize: 12,
      padding: '5px 9px',
      borderRadius: 6,
      color: on ? APP.blue : APP.sub,
      background: on ? APP.blueBg : 'transparent',
      fontWeight: on ? 700 : 400,
      whiteSpace: 'nowrap'
    }
  }, t);
  return React.createElement("div", {
    style: {
      background: APP.bg,
      borderRadius: 14,
      overflow: 'hidden',
      boxShadow: '0 12px 34px rgba(20,20,19,0.18)',
      border: `1px solid ${C.LINE}`,
      color: APP.ink,
      display: 'flex',
      flexDirection: 'column',
      height: '100%'
    }
  }, React.createElement("div", {
    style: {
      background: C.TINT,
      padding: '6px 12px',
      fontFamily: MONO,
      fontSize: 11,
      color: C.GRAY
    }
  }, "localhost:3000 \xB7 \u6982\u8981"), React.createElement("div", {
    style: {
      background: '#fff',
      borderBottom: `1px solid ${APP.line}`,
      padding: '9px 16px',
      display: 'flex',
      alignItems: 'center',
      gap: 14
    }
  }, React.createElement("div", {
    style: {
      whiteSpace: 'nowrap'
    }
  }, React.createElement("b", {
    style: {
      fontSize: 14.5
    }
  }, "\u89E6\u5A92\u30B3\u30F3\u30DD\u30FC\u30CD\u30F3\u30C4"), React.createElement("span", {
    style: {
      fontSize: 10.5,
      color: APP.sub,
      marginLeft: 8
    }
  }, "\u5728\u5EAB\u7BA1\u7406\u30B7\u30B9\u30C6\u30E0")), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 2,
      marginLeft: 'auto'
    }
  }, ['概要', '在庫', '注文', '財務', '需要予測', 'Reports'].map((t, i) => tab(t, i === 0)))), React.createElement("div", {
    style: {
      position: 'relative',
      background: '#fff',
      borderBottom: `1px solid ${APP.line}`,
      padding: '9px 16px 11px',
      display: 'flex',
      gap: 10
    }
  }, React.createElement(Pin, {
    n: 1,
    style: {
      position: 'absolute',
      left: -2,
      top: -8,
      zIndex: 2
    }
  }), sel('期間', 'すべての月', phase === 0), sel('場所', 'すべて', phase === 1), sel('カテゴリ', 'すべて'), sel('注文ステータス', 'すべて')), React.createElement("div", {
    style: {
      padding: '12px 16px',
      flex: 1,
      minHeight: 0,
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 16,
      fontWeight: 700,
      marginBottom: 8
    }
  }, "\u6982\u8981"), React.createElement("div", {
    style: {
      position: 'relative'
    }
  }, React.createElement(Pin, {
    n: 2,
    style: {
      position: 'absolute',
      left: -14,
      top: -4,
      zIndex: 2
    }
  }), React.createElement("div", {
    style: {
      fontSize: 11.5,
      fontWeight: 700,
      color: APP.sub,
      margin: '0 0 6px 16px'
    }
  }, "\u4E3B\u8981\u696D\u7E3E\u8A55\u4FA1\u6307\u6A19"), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 7
    }
  }, kpi('在庫回転率', '4.2', '目標: 4.5 (-6.67%)', '93%'), kpi('注文履行数', '187', '目標: 200 (93.50%)', '93%'), kpi('注文充足率', '96.8%', '目標: 95% (+1.80%)', '100%', true), kpi('収益（注文）年初来', '$31,166,853', '目標: $9.6M (+224.7%)', '100%', false, 1.4), kpi('平均処理時間（日）', '2.8', '目標: 3.0 (-6.67%)', '93%', true, 1.2))), React.createElement("div", {
    style: {
      position: 'relative',
      flex: 1,
      minHeight: 0,
      marginTop: 14,
      display: 'flex',
      gap: 10,
      overflow: 'hidden'
    }
  }, React.createElement("div", {
    style: {
      flex: 1,
      background: APP.card,
      border: `1px solid ${APP.line}`,
      borderRadius: 9,
      padding: '10px 12px'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 12,
      fontWeight: 700,
      marginBottom: 8
    }
  }, "\u6CE8\u6587\u72B6\u6CC1"), React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 14
    }
  }, React.createElement("svg", {
    viewBox: "0 0 42 42",
    style: {
      width: 84,
      height: 84,
      flexShrink: 0
    },
    "aria-hidden": "true"
  }, React.createElement("circle", {
    cx: "21",
    cy: "21",
    r: "15.9",
    fill: "none",
    stroke: "#10b981",
    strokeWidth: "6",
    strokeDasharray: "62 38",
    strokeDashoffset: "25"
  }), React.createElement("circle", {
    cx: "21",
    cy: "21",
    r: "15.9",
    fill: "none",
    stroke: "#3b82f6",
    strokeWidth: "6",
    strokeDasharray: "20 80",
    strokeDashoffset: "63"
  }), React.createElement("circle", {
    cx: "21",
    cy: "21",
    r: "15.9",
    fill: "none",
    stroke: "#f59e0b",
    strokeWidth: "6",
    strokeDasharray: "12 88",
    strokeDashoffset: "43"
  }), React.createElement("circle", {
    cx: "21",
    cy: "21",
    r: "15.9",
    fill: "none",
    stroke: "#ef4444",
    strokeWidth: "6",
    strokeDasharray: "6 94",
    strokeDashoffset: "31"
  })), React.createElement("div", {
    style: {
      fontSize: 11,
      color: APP.sub,
      lineHeight: 1.9
    }
  }, [['#10b981', '配達済み'], ['#3b82f6', '出荷済み'], ['#f59e0b', '処理中'], ['#ef4444', 'バックオーダー']].map(([c, t]) => React.createElement("div", {
    key: t
  }, React.createElement("span", {
    style: {
      display: 'inline-block',
      width: 8,
      height: 8,
      borderRadius: 4,
      background: c,
      marginRight: 6
    }
  }), t))))), React.createElement("div", {
    style: {
      flex: 1,
      background: APP.card,
      border: `1px solid ${APP.line}`,
      borderRadius: 9,
      padding: '10px 12px'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 12,
      fontWeight: 700,
      marginBottom: 10
    }
  }, "\u30AB\u30C6\u30B4\u30EA\u5225\u5728\u5EAB\u4FA1\u5024"), [['回路基板', 92], ['センサー', 74], ['コントローラー', 58], ['アクチュエータ', 46], ['電源', 33]].map(([t, w]) => React.createElement("div", {
    key: t,
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      marginBottom: 7,
      fontSize: 10.5,
      color: APP.sub
    }
  }, React.createElement("span", {
    style: {
      width: 84,
      flexShrink: 0,
      whiteSpace: 'nowrap'
    }
  }, t), React.createElement("span", {
    style: {
      height: 9,
      width: `${w * 0.6}%`,
      background: APP.blue,
      borderRadius: 3,
      opacity: 0.85
    }
  })))), React.createElement("div", {
    style: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 46,
      background: `linear-gradient(rgba(248,250,252,0), ${APP.bg})`
    }
  }))));
}
function Slide_App() {
  const phase = useLoop(2, 1600, 0);
  const pin = n => React.createElement(Pin, {
    n: n,
    size: 20,
    style: {
      verticalAlign: '-4px',
      boxShadow: 'none',
      margin: '0 3px'
    }
  });
  return React.createElement(Slide, {
    label: "The app and R1",
    padding: "40px 72px 58px"
  }, React.createElement(Head, {
    kicker: "\u7B2C2\u5E55\u306E\u984C\u6750",
    h2: ph('最初に直すのは R1：', '概要ページの指標が、', 'フィルターに連動しない')
  }), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 32,
      flex: 1,
      minHeight: 0
    }
  }, React.createElement("div", {
    style: {
      flex: 1.12,
      minWidth: 0
    }
  }, React.createElement(AppMock, {
    phase: phase
  })), React.createElement("div", {
    style: {
      flex: 0.88,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      background: '#fff',
      borderLeft: `4px solid ${C.CLAY}`,
      borderRadius: '0 12px 12px 0',
      padding: '16px 20px',
      boxShadow: '0 1px 0 rgba(31,30,29,0.06)'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 17.5,
      lineHeight: 1.7,
      fontWeight: 500
    }
  }, "\u300C\u6982\u8981\u30DA\u30FC\u30B8\u306E\u4E3B\u8981\u6307\u6A19\uFF08KPI\uFF09\u304C\u3001\u753B\u9762\u4E0A\u90E8\u306E\u671F\u9593\u30FB\u62E0\u70B9\u306A\u3069\u306E\u30D5\u30A3\u30EB\u30BF\u30FC\u3092\u5909\u3048\u3066\u3082\u66F4\u65B0\u3055\u308C\u306A\u3044\u3002\u300D"), React.createElement("div", {
    style: {
      font: `12px/1.4 ${MONO}`,
      color: C.GRAY,
      marginTop: 7
    }
  }, "RFP \xA73.1 \xB7 R1\uFF08\u30AF\u30E9\u30A4\u30A2\u30F3\u30C8\u306E\u6700\u512A\u5148\uFF09")), React.createElement("div", {
    style: {
      fontSize: 15,
      color: C.INK,
      lineHeight: 1.7,
      margin: '14px 0 0'
    }
  }, "\u30AA\u30DA\u30EC\u30FC\u30B7\u30E7\u30F3\u30C1\u30FC\u30E0\u306F\u6570\u5B57\u3092\u4FE1\u7528\u3067\u304D\u305A\u3001\u8868\u8A08\u7B97\u30BD\u30D5\u30C8\u3067\u96C6\u8A08\u3057\u76F4\u3057\u3066\u3044\u307E\u3059\u3002"), React.createElement("div", {
    style: {
      marginTop: 18,
      background: '#fff',
      border: `1.5px solid ${C.CLAY}`,
      borderRadius: 12,
      padding: '14px 18px'
    }
  }, React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.CLAY,
      marginBottom: 5
    }
  }, "\u307E\u305A\u3001\u81EA\u5206\u306E\u76EE\u3067\u78BA\u304B\u3081\u308B"), React.createElement("div", {
    style: {
      fontSize: 16.5,
      lineHeight: 1.75
    }
  }, pin(1), "\u3092\u5207\u308A\u66FF\u3048\u308B\u3068\u3001", pin(2), "\u306E\u3069\u306E\u6570\u5B57\u304C\u5909\u308F\u308A\u3001\u3069\u308C\u304C\u5909\u308F\u3089\u306A\u3044\u304B\u3002")), React.createElement("div", {
    style: {
      marginTop: 'auto',
      background: C.SLATE,
      color: C.IVORY,
      borderRadius: 12,
      padding: '12px 18px',
      fontSize: 14.5,
      lineHeight: 1.6
    }
  }, React.createElement("b", null, "R2\u301CR5 \u306F\u6B21\u306E\u30D5\u30A7\u30FC\u30BA\u3067\u3059\u3002"), "\u4ECA\u65E5\u306E\u9032\u6357\u30EC\u30DD\u30FC\u30C8\u306B\u3001\u5F15\u304D\u7D99\u304E\u3068\u3057\u3066\u307E\u3068\u3081\u307E\u3059\u3002"))));
}
function Shot({
  src,
  url,
  alt,
  flex,
  size,
  pins,
  bg,
  bare,
  fit
}) {
  const body = React.createElement("div", {
    style: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      aspectRatio: String(size)
    }
  }, React.createElement("img", {
    src: src,
    alt: alt,
    style: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: 'auto',
      display: 'block'
    }
  }), (pins || []).map(p => React.createElement("span", {
    key: p.n,
    style: {
      position: 'absolute',
      left: `${p.x}%`,
      top: `${p.y}%`,
      transform: 'translate(-50%, -50%)',
      display: 'inline-flex'
    }
  }, React.createElement(Pin, {
    n: p.n,
    c: p.c
  }))));
  if (bare) {
    return React.createElement("div", {
      style: {
        position: 'relative',
        flex: '0 0 auto',
        width: '100%',
        aspectRatio: String(size),
        background: bg || '#fff',
        border: `1px solid ${C.LINE}`,
        borderRadius: 10,
        overflow: 'hidden',
        boxShadow: '0 6px 18px rgba(20,20,19,0.08)'
      }
    }, body);
  }
  return React.createElement("div", {
    style: {
      flex: flex || 1,
      minHeight: 0,
      minWidth: 0,
      alignSelf: fit ? 'flex-start' : 'stretch',
      display: 'flex',
      flexDirection: 'column',
      background: bg || '#fff',
      border: `1px solid ${C.LINE}`,
      borderRadius: 12,
      overflow: 'hidden',
      boxShadow: '0 10px 28px rgba(20,20,19,0.10)'
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      background: C.TINT,
      padding: '6px 12px',
      fontFamily: MONO,
      fontSize: 12,
      color: C.GRAY,
      flex: '0 0 auto'
    }
  }, React.createElement("span", {
    style: {
      width: 8,
      height: 8,
      borderRadius: 4,
      background: '#D9CFC0'
    }
  }), React.createElement("span", {
    style: {
      width: 8,
      height: 8,
      borderRadius: 4,
      background: '#D9CFC0'
    }
  }), React.createElement("span", {
    style: {
      width: 8,
      height: 8,
      borderRadius: 4,
      background: '#D9CFC0',
      marginRight: 6
    }
  }), React.createElement("span", {
    style: {
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis'
    }
  }, url)), React.createElement("div", {
    style: fit ? {
      position: 'relative',
      aspectRatio: String(size),
      overflow: 'hidden'
    } : {
      flex: 1,
      minHeight: 0,
      position: 'relative',
      overflow: 'hidden'
    }
  }, body));
}
function Callout({
  n,
  c,
  title,
  children
}) {
  return React.createElement("div", {
    style: {
      display: 'flex',
      gap: 11,
      alignItems: 'flex-start'
    }
  }, React.createElement("span", {
    style: {
      position: 'relative',
      top: 2,
      display: 'inline-flex'
    }
  }, React.createElement(Pin, {
    n: n,
    c: c
  })), React.createElement("div", {
    style: {
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      fontSize: 17.5,
      fontWeight: 700,
      lineHeight: 1.35,
      color: C.SLATE
    }
  }, title), React.createElement("div", {
    style: {
      fontSize: 14,
      lineHeight: 1.55,
      color: C.INK,
      marginTop: 1
    }
  }, children)));
}
function Slide_Map() {
  return React.createElement(Slide, {
    label: "Live map",
    padding: "40px 72px 56px"
  }, React.createElement(Head, {
    kicker: "\u9014\u4E2D\u3067",
    h2: ph('「いまどこ？」ページが、', '現在地とペースを示し続ける')
  }), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 26,
      flex: 1,
      minHeight: 0
    }
  }, React.createElement(Shot, {
    fit: true,
    flex: 1.25,
    src: "assets/map-top.png",
    size: 1300 / 910,
    url: "localhost:8766/map.html",
    alt: "\u30B9\u30C6\u30C3\u30D7 09 \u306E\u6642\u70B9\u306E\u300C\u3044\u307E\u3069\u3053\uFF1F\u300D\u30DA\u30FC\u30B8\u306E\u4E0A\u534A\u5206\u3002\u73FE\u5728\u306E\u30B9\u30C6\u30C3\u30D7\u3001\u7D4C\u904E\u6642\u9593\u3001\u4E88\u5B9A\u7D42\u4E86\u3001\u30DA\u30FC\u30B9\u300190 \u5206\u306E\u4E88\u7B97\u306E\u5E2F\u3001\u3044\u307E\u3084\u308B\u3053\u3068",
    pins: [{
      n: 1,
      x: 22,
      y: 30.4
    }, {
      n: 2,
      x: 67.5,
      y: 63.8
    }, {
      n: 3,
      x: 42,
      y: 80.6
    }]
  }), React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: 11
    }
  }, React.createElement(Callout, {
    n: 1,
    title: "\u73FE\u5728\u5730\u304C 1 \u884C\u3067\u308F\u304B\u308B"
  }, "\u3044\u307E\u306E\u30B9\u30C6\u30C3\u30D7\u3068\u3001\u5B8C\u4E86\u3057\u305F\u6570\u3002\u3053\u306E\u30BF\u30D6\u306F\u958B\u3044\u305F\u307E\u307E\u306B\u3057\u307E\u3059\u3002"), React.createElement(Callout, {
    n: 2,
    title: "90 \u5206\u306E\u4E88\u7B97\u3068\u30DA\u30FC\u30B9"
  }, "\u5E2F\u304C\u7D4C\u904E\u6642\u9593\u3001\u7E26\u7DDA\u304C\u3044\u307E\u306E\u30B9\u30C6\u30C3\u30D7\u306E\u4E88\u5B9A\u7D42\u4E86\u3002\u9045\u308C\u305F\u3089\u3001Claude \u304C\u6B21\u3092\u77ED\u3081\u306B\u904B\u3073\u307E\u3059\u3002"), React.createElement(Callout, {
    n: 3,
    title: "\u3044\u307E\u3084\u308B\u3053\u3068"
  }, "\u30BF\u30FC\u30DF\u30CA\u30EB\u306B\u623B\u3089\u306A\u304F\u3066\u3082\u3001\u6B21\u306E\u4E00\u624B\u304C\u308F\u304B\u308A\u307E\u3059\u3002"), React.createElement(Shot, {
    bare: true,
    src: "assets/map-act2.png",
    size: 1100 / 480,
    alt: "\u540C\u3058\u30DA\u30FC\u30B8\u306E\u4E0B\u306B\u3042\u308B\u5168\u4F53\u30DE\u30C3\u30D7\u306E\u7B2C2\u5E55\u3002\u7D42\u308F\u3063\u305F\u30B9\u30C6\u30C3\u30D7\u306B\u306F\u30C1\u30A7\u30C3\u30AF\u3068\u5B8C\u4E86\u6642\u523B\u304C\u4ED8\u304D\u3001\u3044\u307E\u306E\u30B9\u30C6\u30C3\u30D7\u306F\u9ED2\u3044\u5E2F\u3067\u793A\u3055\u308C\u308B",
    pins: [{
      n: 4,
      x: 66,
      y: 24.5
    }]
  }), React.createElement(Callout, {
    n: 4,
    title: "\u5168\u4F53\u30DE\u30C3\u30D7"
  }, "\u30C1\u30A7\u30C3\u30AF\u306F\u3001Claude \u304C\u5B8C\u4E86\u3092\u78BA\u304B\u3081\u305F\u6642\u70B9\u3067\u4ED8\u304D\u307E\u3059\u3002"))));
}
function Slide_Report() {
  const G = C.GREEN;
  const chip = t => React.createElement("span", {
    key: t,
    style: {
      fontSize: 12.5,
      padding: '3px 8px',
      borderRadius: 6,
      background: '#fff',
      border: `1px solid ${C.LINE}`,
      color: C.INK,
      whiteSpace: 'nowrap'
    }
  }, t);
  return React.createElement(Slide, {
    label: "Progress report",
    padding: "40px 72px 56px"
  }, React.createElement(Head, {
    kicker: "\u6700\u5F8C\u306B",
    h2: ph('今日の進捗を、', 'レポートに自動でまとめる')
  }), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 26,
      flex: 1,
      minHeight: 0
    }
  }, React.createElement(Shot, {
    fit: true,
    flex: 1.25,
    src: "assets/report-top.png",
    size: 1300 / 894,
    url: "localhost:8766/proposal/progress-report.html",
    alt: "\u9032\u6357\u30EC\u30DD\u30FC\u30C8\u306E\u5192\u982D\u3002\u4ECA\u65E5\u306E\u898B\u51FA\u3057\u3068\u8981\u7D04\u3001\u65E5\u4ED8\u3001\u6848\u4EF6\u3001\u5B8C\u4E86\u3057\u305F\u30B9\u30C6\u30C3\u30D7\u3001\u304B\u304B\u3063\u305F\u6642\u9593\u3002\u305D\u306E\u4E0B\u306B\u6982\u8981\u306E 4 \u3064\u306E\u6570\u5B57",
    pins: [{
      n: 1,
      x: 95.5,
      y: 17.3,
      c: G
    }, {
      n: 2,
      x: 50,
      y: 78.2,
      c: G
    }]
  }), React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: 11
    }
  }, React.createElement(Callout, {
    n: 1,
    c: G,
    title: "\u4ECA\u65E5\u306E\u6210\u679C\u3092\u3001\u898B\u51FA\u3057\u3072\u3068\u3064\u3067"
  }, "\u6587\u7AE0\u306F Claude \u304C\u66F8\u304D\u3001\u6570\u5B57\u306F\u3042\u306A\u305F\u306E\u5B9F\u884C\u8A18\u9332\u304B\u3089\u53D6\u308A\u307E\u3059\u3002"), React.createElement(Callout, {
    n: 2,
    c: G,
    title: "\u6982\u8981\u306E\u6570\u5B57"
  }, "\u6210\u679C\u7269\u3001\u7D0D\u54C1\u3057\u305F\u30B3\u30DF\u30C3\u30C8\u3001\u30C6\u30B9\u30C8\u3001\u304B\u304B\u3063\u305F\u6642\u9593\u3002"), React.createElement(Shot, {
    bare: true,
    src: "assets/report-timeline.png",
    size: 1100 / 498,
    alt: "\u540C\u3058\u30EC\u30DD\u30FC\u30C8\u306E\u30BF\u30A4\u30E0\u30E9\u30A4\u30F3\u30021 \u30B9\u30C6\u30C3\u30D7\u306B\u3064\u304D 1 \u884C\u3067\u3001\u76EE\u5B89\u306E\u6642\u9593\u306E\u5E2F\u3068\u3001\u5B9F\u969B\u306B\u304B\u304B\u3063\u305F\u6642\u9593\u306E\u5E2F\u304C\u4E26\u3076",
    pins: [{
      n: 3,
      x: 56,
      y: 39,
      c: G
    }]
  }), React.createElement(Callout, {
    n: 3,
    c: G,
    title: "\u4E88\u5B9A\u3068\u5B9F\u7E3E\u306E\u30BF\u30A4\u30E0\u30E9\u30A4\u30F3"
  }, nb('1 ステップ'), "\u306B\u3064\u304D ", nb('1 行'), "\u3002\u76EE\u5B89\u306E\u6642\u9593\u3068\u3001\u5B9F\u969B\u306E\u6642\u9593\u3002"), React.createElement("div", {
    style: {
      marginTop: 'auto'
    }
  }, React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.1em',
      color: C.GRAY,
      marginBottom: 5
    }
  }, "\u3055\u3089\u306B\u4E0B"), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 5,
      flexWrap: 'wrap'
    }
  }, ['提案書', '納品', 'コードレビュー', '判断と軌道修正', '引き継ぎ', '使った機能'].map(chip))))));
}
function Slide_Keep() {
  const dim = 'rgba(250,249,245,0.55)';
  const row = (glyph, name, what, c) => React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'baseline',
      gap: 18,
      padding: '7px 0'
    }
  }, React.createElement("span", {
    style: {
      fontFamily: MONO,
      fontSize: 17,
      whiteSpace: 'pre',
      width: '44%',
      flexShrink: 0
    }
  }, React.createElement("span", {
    style: {
      color: dim
    }
  }, glyph), React.createElement("span", {
    style: {
      color: c || C.IVORY
    }
  }, name)), React.createElement("span", {
    style: {
      fontSize: 16,
      color: 'rgba(250,249,245,0.82)',
      lineHeight: 1.5
    }
  }, what));
  return React.createElement(Slide, {
    bg: C.SLATE,
    color: C.IVORY,
    label: "What you keep",
    padding: "42px 72px 60px"
  }, React.createElement(Head, {
    dark: true,
    kicker: "\u7D42\u308F\u3063\u305F\u3042\u3068",
    h2: ph('作ったものは、', 'リポジトリのファイルとコミットとして', '手元に残る')
  }), React.createElement("div", {
    style: {
      flex: 1,
      minHeight: 0,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      background: 'rgba(250,249,245,0.05)',
      border: '1px solid rgba(250,249,245,0.14)',
      borderRadius: 14,
      padding: '14px 30px'
    }
  }, row('', 'meridian-workshop-jp/', 'あなたの fork', '#E8A48C'), row('├─ ', 'proposal/', ''), row('│  ├─ ', 'proposal.md', React.createElement("span", null, "\u3042\u306A\u305F\u306E", nb(' 4 つ'), "\u306E\u5224\u65AD\u3092\u3082\u3068\u306B\u3001Claude \u304C\u66F8\u3044\u305F\u63D0\u6848\u66F8"), '#E8A48C'), row('│  ├─ ', 'proposal.html', '同じ提案書の、読む用のページ', '#E8A48C'), row('│  ├─ ', 'capabilities-deck.html', '同じ提案書の、プレゼン用のスライド', '#E8A48C'), row('│  └─ ', 'progress-report.html', '今日の成果、レビューの指摘と判断、次フェーズへの引き継ぎ', '#9CC3B5'), row('└─ ', 'client/ · server/', React.createElement("span", null, "\u30D6\u30E9\u30F3\u30C1 ", React.createElement("span", {
    style: {
      fontFamily: MONO,
      fontSize: 15
    }
  }, "fix/overview-filters"))), row('   ● ', '概要ページの KPI を直したコミット', '', '#9CC3B5'), row('   ● ', 'レビューの指摘を直したコミット', '', '#9CC3B5')), React.createElement("div", {
    style: {
      marginTop: 14,
      display: 'flex',
      alignItems: 'center',
      gap: 14,
      fontSize: 16
    }
  }, React.createElement("span", {
    style: {
      background: C.CLAY,
      color: '#fff',
      borderRadius: 999,
      padding: '7px 16px',
      fontWeight: 700,
      whiteSpace: 'nowrap'
    }
  }, "fork \u306B push \u2192 Pull Request"), React.createElement("span", {
    style: {
      color: 'rgba(250,249,245,0.82)'
    }
  }, "\u6700\u5F8C\u306B Pull Request \u3092\u4F5C\u308B\u3068\u3053\u308D\u307E\u3067\u3001Claude \u304C\u624B\u4F1D\u3044\u307E\u3059\u3002")));
}
function Slide_Help() {
  const term = lines => React.createElement("div", {
    style: {
      marginTop: 'auto',
      background: C.SLATE,
      borderRadius: 10,
      padding: '13px 16px',
      fontFamily: MONO,
      fontSize: 14.5,
      lineHeight: 1.75,
      color: 'rgba(250,249,245,0.9)'
    }
  }, lines.map(([who, t], i) => React.createElement("div", {
    key: i,
    style: {
      display: 'flex',
      gap: 8
    }
  }, React.createElement("span", {
    style: {
      color: who === 'claude' ? 'rgba(250,249,245,0.5)' : C.CLAY,
      flexShrink: 0
    }
  }, who === 'claude' ? '◆' : who === 'out' ? ' ' : who === 'you' ? '>' : '$'), React.createElement("span", {
    style: {
      color: who === 'out' ? '#9CC3B5' : who === 'claude' ? 'rgba(250,249,245,0.9)' : C.IVORY
    }
  }, t))));
  const card = (k, t, body, lines) => React.createElement("div", {
    style: {
      flex: 1,
      background: '#fff',
      border: `1px solid ${C.LINE}`,
      borderRadius: 14,
      padding: '22px 26px',
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      font: `600 13.5px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.CLAY
    }
  }, k), React.createElement("div", {
    style: {
      fontSize: 27,
      fontWeight: 700,
      lineHeight: 1.4,
      margin: '8px 0 10px'
    }
  }, t), React.createElement("div", {
    style: {
      fontSize: 17,
      color: C.INK,
      lineHeight: 1.75,
      marginBottom: 16
    }
  }, body), term(lines));
  return React.createElement(Slide, {
    label: "Help",
    padding: "42px 72px 58px"
  }, React.createElement(Head, {
    kicker: "\u77E5\u3063\u3066\u304A\u304F\u3068\u3088\u3044\u3053\u3068",
    h2: ph('行き詰まっても、中断しても、', '続きから再開できる')
  }), React.createElement("div", {
    style: {
      flex: 1,
      minHeight: 0,
      display: 'flex',
      alignItems: 'center'
    }
  }, React.createElement("div", {
    style: {
      display: 'flex',
      gap: 16,
      alignItems: 'stretch',
      width: '100%'
    }
  }, card('行き詰まったら', ph('そのまま Claude に', '伝えます。'), '足りないものを一緒に片付けます。時間がなければ、確認して先へ進めます。', [['you', 'アプリが起動しません'], ['claude', 'uv が見つからないようです。入れ方を案内します。']]), card('中断するとき', ph('./start.sh を', 'もう一度実行します。'), 'いつ終了しても構いません。同じステップから再開します。', [['sh', './start.sh'], ['you', 'こんにちは'], ['claude', 'おかえりなさい。ステップ 08 の続きから始めます。']]), card('やり直すとき', ph('スクリプト 1 つで', '戻せます。'), 'リポジトリを出発点に戻します。作業は、退避用のブランチに残ります。', [['sh', './reset-demo.sh'], ['out', 'これまでの作業はブランチ tutor-backup-20260923-141205 に残しました。'], ['out', 'リセットしました。']]))));
}
function Slide_Start() {
  const need = (t, s) => React.createElement("div", {
    style: {
      display: 'flex',
      gap: 10,
      alignItems: 'baseline',
      padding: '9px 0',
      borderBottom: `1px solid ${C.LINE}`
    }
  }, React.createElement("b", {
    style: {
      fontSize: 17,
      width: 160,
      flexShrink: 0
    }
  }, t), React.createElement("span", {
    style: {
      fontSize: 14.5,
      color: C.GRAY,
      lineHeight: 1.5
    }
  }, s));
  const ln = (n, body) => React.createElement("div", null, React.createElement("span", {
    style: {
      color: C.CLAY
    }
  }, n), "\xA0\xA0", body);
  return React.createElement(Slide, {
    label: "Start",
    padding: "40px 72px 58px"
  }, React.createElement(Head, {
    kicker: "\u59CB\u3081\u65B9",
    h2: ph('リポジトリを clone して、', 'コマンドを 1 つ実行する')
  }), React.createElement("div", {
    style: {
      background: C.SLATE,
      borderRadius: 14,
      padding: '12px 28px',
      fontFamily: MONO,
      fontSize: 18,
      lineHeight: 2,
      whiteSpace: 'nowrap',
      color: C.IVORY,
      boxShadow: '0 10px 30px rgba(0,0,0,0.18)'
    }
  }, ln(1, 'git clone https://github.com/yuki-ant/meridian-workshop-jp'), ln(2, React.createElement("span", null, "cd meridian-workshop-jp && ./start.sh", React.createElement("span", {
    style: {
      fontFamily: SANS,
      fontSize: 14,
      color: 'rgba(250,249,245,0.5)',
      marginLeft: 22
    }
  }, "Windows \u3067\u306F start.cmd"))), React.createElement("div", {
    style: {
      borderTop: '1px solid rgba(250,249,245,0.18)',
      marginTop: 4
    }
  }, React.createElement("span", {
    style: {
      color: C.CLAY
    }
  }, "3"), "\xA0\xA0", React.createElement("span", {
    style: {
      color: 'rgba(250,249,245,0.6)'
    }
  }, ">"), " \u3053\u3093\u306B\u3061\u306F", React.createElement("span", {
    style: {
      fontFamily: SANS,
      fontSize: 14,
      color: 'rgba(250,249,245,0.5)',
      marginLeft: 22
    }
  }, "Claude \u304C\u8D77\u52D5\u3057\u305F\u3089\u3001\u3053\u3046\u8A71\u3057\u304B\u3051\u307E\u3059"))), React.createElement("div", {
    style: {
      display: 'flex',
      gap: 36,
      flex: 1,
      minHeight: 0,
      alignItems: 'stretch',
      marginTop: 14
    }
  }, React.createElement("div", {
    style: {
      flex: 1.12,
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      minWidth: 0
    }
  }, React.createElement("div", {
    style: {
      fontSize: 15,
      color: C.GRAY,
      lineHeight: 1.75
    }
  }, code('start.sh', 14), " \u306F\u3001\u30C1\u30E5\u30FC\u30BF\u30FC\u306E\u30D7\u30E9\u30B0\u30A4\u30F3\u3092\u3053\u306E\u30BB\u30C3\u30B7\u30E7\u30F3\u306B\u3060\u3051\u8AAD\u307F\u8FBC\u3093\u3067 ", code('claude', 14), " \u3092\u8D77\u52D5\u3057\u307E\u3059\u3002\u6700\u5F8C\u306B Pull Request \u3092\u4F5C\u308A\u305F\u3044\u65B9\u306F\u3001\u5148\u306B GitHub \u3067 fork \u3057\u3066\u3001\u81EA\u5206\u306E fork \u3092 clone \u3057\u3066\u304F\u3060\u3055\u3044\u3002"), React.createElement("div", {
    style: {
      background: '#fff',
      border: `1.5px solid ${C.CLAY}`,
      borderRadius: 12,
      padding: '13px 20px'
    }
  }, React.createElement("div", {
    style: {
      fontSize: 21,
      fontWeight: 700,
      marginBottom: 3
    }
  }, "\u3042\u306A\u305F\u306E Claude Code \u306B\u306F\u3001\u4F55\u3082\u8FFD\u52A0\u3055\u308C\u307E\u305B\u3093\u3002"), React.createElement("div", {
    style: {
      fontSize: 14.5,
      color: C.INK,
      lineHeight: 1.65
    }
  }, "\u30C1\u30E5\u30FC\u30BF\u30FC\uFF08Claude \u3092\u6848\u5185\u5F79\u306B\u3059\u308B\u30D7\u30E9\u30B0\u30A4\u30F3\uFF09\u304C\u50CD\u304F\u306E\u306F\u3001\u3053\u306E\u30BB\u30C3\u30B7\u30E7\u30F3\u3060\u3051\u3067\u3059\u3002\u307B\u304B\u306E\u5834\u6240\u3067 ", code('claude', 13.5), " \u3092\u8D77\u52D5\u3057\u305F\u3068\u304D\u306E\u52D5\u304D\u306F\u5909\u308F\u308A\u307E\u305B\u3093\u3002"))), React.createElement("div", {
    style: {
      flex: 0.88,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column'
    }
  }, React.createElement("div", {
    style: {
      font: `600 12px/1.4 ${MONO}`,
      letterSpacing: '0.12em',
      color: C.GRAY
    }
  }, "\u5FC5\u8981\u306A\u3082\u306E"), need('Claude Code', 'インストール済み、サインイン済み'), need('Node.js 18 以上', 'チューターとフロントエンドが使用'), need('uv', '第2幕でバックエンドが使用。なければ Claude が案内'), need('Python 3.11 以上', '第2幕でバックエンドが使用'), need('git', 'リポジトリを clone し、作業をコミット'), need('ブラウザ', '「いまどこ？」ページと、読むページを表示'))), React.createElement("div", {
    style: {
      marginTop: 12,
      background: C.CLAY,
      color: '#fff',
      borderRadius: 12,
      padding: '12px 22px',
      display: 'flex',
      alignItems: 'center',
      gap: 18,
      boxShadow: '0 6px 24px rgba(0,0,0,0.15)'
    }
  }, React.createElement("span", {
    style: {
      fontSize: 20,
      fontWeight: 700,
      whiteSpace: 'nowrap'
    }
  }, "\u3067\u306F\u3001\u30BF\u30FC\u30DF\u30CA\u30EB\u3078\u3002"), React.createElement("span", {
    style: {
      fontSize: 15,
      lineHeight: 1.6
    }
  }, "Claude \u304C\u5F85\u3063\u3066\u3044\u308B\u65B9\u306F\u3001\u623B\u3063\u3066 ", React.createElement("b", {
    style: {
      fontFamily: MONO
    }
  }, "Done"), " \u3068\u9001\u3063\u3066\u304F\u3060\u3055\u3044\u3002\u3053\u308C\u304B\u3089\u59CB\u3081\u308B\u65B9\u306F\u3001\u4E0A\u306E\u30B3\u30DE\u30F3\u30C9\u3092\u5B9F\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002")));
}
function Slide_Thanks() {
  return React.createElement(Slide, {
    bg: C.SLATE,
    color: C.IVORY,
    label: "Thanks",
    center: true
  }, React.createElement("span", {
    style: {
      width: 44,
      height: 4,
      background: C.CLAY,
      display: 'inline-block',
      borderRadius: 2,
      marginBottom: 30
    }
  }), React.createElement("h1", {
    style: {
      fontSize: 54,
      fontWeight: 700,
      letterSpacing: '-0.01em',
      margin: '0 0 16px'
    }
  }, "\u3042\u308A\u304C\u3068\u3046\u3054\u3056\u3044\u307E\u3057\u305F"), React.createElement("div", {
    style: {
      fontSize: 24,
      fontWeight: 500,
      color: C.CLAY,
      textAlign: 'center'
    }
  }, "\u3053\u3053\u304B\u3089\u306F\u3001Claude \u304C\u6848\u5185\u3057\u307E\u3059\u3002"));
}
const SLIDES = [{
  c: Slide_Title,
  title: 'Claude が Claude を教える',
  notes: 'パートナー向けの、セルフペース型の Claude ハンズオンワークショップです。進めるのは講師ではなく、Claude Code 自身です。あなたのターミナルの中で、約 90 分かけて 1 ステップずつ案内します。題材は、Meridian Components という架空のクライアントの RFP です。第1幕でコンサルタントとして応札し、受注した第2幕で、最初の改修を納品します。'
}, SHOW_SPEAKER && window.PRESENTER && window.PRESENTER.name && {
  c: Slide_Speaker,
  title: '講師紹介',
  notes: '自己紹介です。名前と所属、これまでの経歴を、30 秒ほどで話します。'
}, {
  c: Slide_How,
  title: 'Claude が 1 ステップずつ案内し、あなたが判断して手を動かす',
  notes: '進み方は、いつも同じです。Claude が次にやることと目安の時間を伝えます。短いページを読むこともあります。読み終えたり、作業が終わったりしたら、ターミナルに戻って「Done」と送ります。「できました」でも構いません。スラッシュコマンド、Shift+Tab、@ によるファイル参照、許可の確認は、あなたにしか入力できないので、Claude は何を入力するかを伝えて待ちます。そのあと Claude が、リポジトリの状態と記録を見て、そのステップの完了条件が満たされているかを確かめます。読むだけのステップは、「Done」でそのまま進みます。[ターミナル、ページ、緑の囲みの順に指す]'
}, {
  c: Slide_Case,
  title: 'あなたはコンサルタント。Meridian Components から RFP が届いた',
  notes: 'あなたの役は、RFP に応札するコンサルタントです。クライアントは Meridian Components。産業用オートメーション部品のディストリビューターで、倉庫はサンフランシスコ、ロンドン、東京にあります。依頼は、在庫管理ダッシュボードのモダナイズと機能拡張です。必須項目は R1 から R5 までで、優先順位順に並んでいます。最優先の R1 が、今日の第2幕で直すものです。手元には、RFP の本体、自社でまとめた背景メモ、前任ベンダーの引き継ぎメモ、そしてソースコードがあります。エンジニアでなくても進められます。決めるのはあなたで、提案書の文章とコードは Claude が書きます。'
}, {
  c: Slide_Agenda,
  title: '応札する第1幕、納品する第2幕、最後に進捗レポート',
  notes: '全体は 12 ステップです。第1幕は約 34 分。RFP とは何かを読み、実際の RFP を @ で読み込み、決めないと見積もれない点を探し、提案の方針を 4 つ決めます。提案書の文章は Claude が一気に書き、HTML のページとスライドにもします。第2幕は約 51 分。/start でアプリを起動して症状を確かめ、Plan Mode で原因を調べ、直してコミットし、サブエージェントのレビューから直す指摘を選びます。いちばん長いのは R1 を直すステップで、22 分です。最後に Claude が進捗レポートを作ります。合計は約 85 分で、5 分ほどの予備があります。色付きのラベルは、そのステップで初めて使う Claude Code の機能です。必要になったときに Claude が紹介します。'
}, {
  c: Slide_App,
  title: '最初に直すのは R1：概要ページの指標が、フィルターに連動しない',
  notes: '第2幕で手を入れるのが、このアプリです。Vue 3 と FastAPI の小さな在庫ダッシュボードで、データは JSON ファイル、データベースはありません。画面の上に期間や場所のフィルターがあり、その下に主要な指標が並びます。RFP には、フィルターを変えても指標が更新されない、と書かれています。ただし、書かれているのは症状だけです。どの数字が変わって、どれが変わらないのかは、アプリを起動して自分の目で確かめます。そのうえで Plan Mode で原因を調べ、直してコミットし、サブエージェントにレビューさせます。R2 から R5 は次のフェーズで、最後のレポートに引き継ぎとしてまとめます。[1 番のフィルター、2 番の指標の順に指す]'
}, {
  c: Slide_Map,
  title: '「いまどこ？」ページが、現在地とペースを示し続ける',
  notes: '進行中の様子です。最初のステップで Claude がこのページをブラウザで開き、あとは自動で更新し続けます。タブは開いたままにしておいてください。1 番、いまのステップと完了した数。2 番、90 分の予算に対する経過時間の帯と、いまのステップを予定どおり終えたときの時刻を示す縦線。3 番、いまやること。4 番、同じページの下にある全体マップです。チェックは「Done」と言った時点ではなく、Claude が完了を確かめた時点で付きます。画面は、サンプルのデータで表示した例です。'
}, {
  c: Slide_Report,
  title: '今日の進捗を、レポートに自動でまとめる',
  notes: '終わったときの様子です。最後のステップで Claude にレポートを頼むと、数字はチューターが実行記録から埋め、文章は Claude が書いて、ブラウザで開きます。コンサルタントがクライアントと自社に渡す進捗レポートの形になっていて、今日の成果、予定と実績のタイムライン、提案書、納品したコミット、コードレビュー、判断と軌道修正、そして次フェーズへの引き継ぎが 1 ページにまとまります。画面は、サンプルのデータで表示した例です。'
}, {
  c: Slide_Keep,
  title: '作ったものは、リポジトリのファイルとコミットとして手元に残る',
  notes: 'ここで作るものは、どれもリポジトリの中の実際のファイルとコミットです。proposal フォルダーには、提案書と、その HTML ページとスライド、そして進捗レポートが入ります。コードの変更は、作業ブランチ fix/overview-filters のコミットとして残ります。概要ページを直したコミットと、レビューの指摘を直したコミットです。最後に、自分の fork に push して Pull Request を作るところまで、Claude が手伝います。'
}, {
  c: Slide_Help,
  title: '行き詰まっても、中断しても、続きから再開できる',
  notes: '行き詰まったら、そのまま Claude に伝えてください。足りないものを一緒に片付けるか、時間がなければ確認のうえで先へ進めます。中断したときは、start.sh をもう一度実行すれば同じステップに戻れます。進捗は tutor/state フォルダーに保存されています。最初からやり直すときは reset-demo.sh です。それまでの作業は退避用のブランチに残ります。'
}, {
  c: Slide_Start,
  title: 'リポジトリを clone して、コマンドを 1 つ実行する',
  notes: '始め方です。リポジトリを clone して、start.sh を実行し、Claude に「こんにちは」と声をかけるだけです。最後に Pull Request を作りたい方は、先に GitHub で fork して、自分の fork を clone してください。start.sh は、このセッションにだけチューターのプラグインを読み込んで Claude Code を起動します。あなたの Claude Code には何も追加されません。必要なのは、Claude Code、Node.js 18 以上、uv、Python 3.11 以上、git、ブラウザです。uv と Python は第2幕まで使いません。では、ターミナルに戻りましょう。Claude が待っている方は「Done」と送ってください。これから始める方は、このコマンドを実行してください。'
}, {
  c: Slide_Thanks,
  title: 'ありがとうございました',
  notes: '説明は以上です。ここからは、Claude が 1 ステップずつ案内します。ご質問があればどうぞ。'
}].filter(Boolean);
mountDeck(SLIDES);
})();
