#!/usr/bin/env node
// Builds the introduction deck that the page server shows in step 01 (tutor/pages/intro/).
// Learners never run this: the built deck.js and React's production builds are committed, so the
// browser needs no Babel and no CDN, and the page also opens from file:// when localhost is out of reach.
//
//   node tutor/maint/intro-deck/build.mjs            compile shell.jsx + slides.jsx into tutor/pages/intro/deck.js
//   node tutor/maint/intro-deck/build.mjs --check    exit 1 when deck.js was built from different sources (needs no Babel)
//   node tutor/maint/intro-deck/build.mjs --vendor   copy React's production builds into tutor/pages/intro/vendor/
//
// The build needs @babel/standalone 7.x, which this repository deliberately does not carry:
//   npm i --no-save --prefix /some/dir @babel/standalone@7        (add react@18 react-dom@18 for --vendor)
//   BUILD_MODULES=/some/dir/node_modules node tutor/maint/intro-deck/build.mjs

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(HERE, "..", "..", "pages", "intro");
const OUT = path.join(OUT_DIR, "deck.js");
// Order matters: the shell defines Slide and mountDeck, the slides file ends by calling mountDeck.
const SOURCES = ["shell.jsx", "slides.jsx"];
const VENDOR = [
  ["react", "umd/react.production.min.js"],
  ["react-dom", "umd/react-dom.production.min.js"],
];

function sources() {
  return SOURCES.map((f) => fs.readFileSync(path.join(HERE, f), "utf8").replace(/\r\n/g, "\n"));
}
function digest(parts) {
  return crypto.createHash("sha256").update(parts.join("\n/* ── */\n")).digest("hex").slice(0, 16);
}
function moduleDirs() {
  return [process.env.BUILD_MODULES, path.join(HERE, "node_modules"), path.resolve(HERE, "..", "..", "..", "node_modules")].filter(Boolean);
}
function resolveFrom(name) {
  for (const dir of moduleDirs()) {
    try {
      return createRequire(path.join(dir, "_")).resolve(name);
    } catch {
      /* try the next directory */
    }
  }
  return null;
}
function missing(what) {
  console.error(`${what} が見つかりません。ビルド用の依存はこのリポジトリに入れていません。次のように用意してください:\n`);
  console.error("  npm i --no-save --prefix /some/dir @babel/standalone@7 react@18 react-dom@18");
  console.error("  BUILD_MODULES=/some/dir/node_modules node tutor/maint/intro-deck/build.mjs\n");
  process.exit(2);
}

const mode = process.argv[2] || "";

if (mode === "--check") {
  const want = digest(sources());
  let have = "";
  try {
    have = (fs.readFileSync(OUT, "utf8").match(/source sha256:([0-9a-f]{16})/) || [])[1] || "";
  } catch {
    /* no build yet */
  }
  const gone = VENDOR.map(([, f]) => path.join(OUT_DIR, "vendor", path.basename(f))).filter((f) => !fs.existsSync(f));
  if (have !== want) console.error(`deck.js はいまの shell.jsx / slides.jsx から作られていません（${have || "なし"} ≠ ${want}）。build.mjs を実行してください。`);
  for (const f of gone) console.error(`足りません: ${path.relative(process.cwd(), f)}（build.mjs --vendor）`);
  process.exit(have === want && gone.length === 0 ? 0 : 1);
}

if (mode === "--vendor") {
  fs.mkdirSync(path.join(OUT_DIR, "vendor"), { recursive: true });
  for (const [pkg, file] of VENDOR) {
    const pj = resolveFrom(`${pkg}/package.json`);
    if (!pj) missing(pkg);
    const from = path.join(path.dirname(pj), file);
    const to = path.join(OUT_DIR, "vendor", path.basename(file));
    fs.copyFileSync(from, to);
    console.log(`${pkg} ${JSON.parse(fs.readFileSync(pj, "utf8")).version} → ${path.relative(process.cwd(), to)}`);
  }
  process.exit(0);
}

const babelPath = resolveFrom("@babel/standalone");
if (!babelPath) missing("@babel/standalone");
const Babel = createRequire(import.meta.url)(babelPath);
const parts = sources();
const compiled = parts.map(
  (src, i) =>
    Babel.transform(src, {
      filename: SOURCES[i],
      presets: [["react", { runtime: "classic" }]],
      comments: false,
      compact: false,
    }).code,
);
const banner = `/* GENERATED by tutor/maint/intro-deck/build.mjs from ${SOURCES.join(" + ")} · source sha256:${digest(parts)} · do not edit, edit the .jsx and rebuild */`;
fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, `${banner}\n(function () {\n"use strict";\n${compiled.join("\n\n")}\n})();\n`);
console.log(`${path.relative(process.cwd(), OUT)} · ${(fs.statSync(OUT).size / 1024).toFixed(1)} KB · Babel ${Babel.version}`);
